Validator Base Module
resuelve/bali pull request #14
Opened 2023-02-10 21:14 UTC by poncho

## Context

Instead of having to create a function for each different document we need for every country, we added a base module that creates this function for each specified document in the `use` command.

### Example

```elixir
  use Bali.Validator,
    country: :pt,
    documents: %{
      nif: ~r/^\d{9}$/
    }

```

2023-02-13 16:33 UTC, CevaMenelao requested changes

2023-02-13 16:33 UTC, CevaMenelao commented on lib/validators/portugal.ex
> +  Validator for Portuguese personal and tax identifications.any()
` .any() ` ?

2023-02-13 16:33 UTC, CevaMenelao commented on lib/bali/validator.ex
> +              true
Ates regresaba un tipo ` {:ok, String.t()} `. No sería bueno mantenerlo?

2023-02-13 16:33 UTC, CevaMenelao commented on lib/validators/portugal.ex
> +  ### nif - Número de Identificação Fiscal
` Identificação ` 👀  y está en español

2023-02-15 19:24 UTC, poncho commented on lib/validators/portugal.ex
> +  ### nif - Número de Identificação Fiscal
Está en portugues 😆

2023-02-15 19:25 UTC, poncho commented on lib/bali/validator.ex
> +              true
Con lo que se habló en el canal se dejó que se mantenga `:valid | {:error, String.t()}` como spec de respuesta

2025-12-23 20:11 UTC, poncho commented
Si en algun momento se necesita se desarrollara

2025-12-23 20:11 UTC, closed without merging